//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiceAgentWebsite.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BILL()
        {
            this.BILL_PRODUCTS = new HashSet<BILL_PRODUCTS>();
        }
    
        public int BILLID { get; set; }
        public Nullable<int> CUSTOMERID { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<System.DateTime> DATE_CLOSED { get; set; }
        public string PAYMENT_METHOD { get; set; }
        public Nullable<int> TYPEID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual BILL_TYPE BILL_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_PRODUCTS> BILL_PRODUCTS { get; set; }
    }
}
