//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiceAgentWebsite.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public int STAFFID { get; set; }
        public string USERNAME { get; set; }
        public string FULLNAME { get; set; }
        public string PHONE { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
    }
}
