//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiceAgentWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RAMS_DBSEntities : DbContext
    {
        public RAMS_DBSEntities()
            : base("name=RAMS_DBSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNT { get; set; }
        public virtual DbSet<BILL> BILL { get; set; }
        public virtual DbSet<BILL_PRODUCTS> BILL_PRODUCTS { get; set; }
        public virtual DbSet<BILL_TYPE> BILL_TYPE { get; set; }
        public virtual DbSet<CART> CART { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<PRODUCT_TYPE> PRODUCT_TYPE { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<STAFF> STAFF { get; set; }
    }
}
